### ISSUE TITLE
Feature request: Add TalentTreeTweaks Enhancements to the Spell Book Window with Space Optimization

### ISSUE THREAD

**Issue by I-AM-T3X** [NumyAddon/TalentTreeTweaks#41]
Hello,

Thank you for your excellent work on the TalentTreeTweaks addon. The enhancements you’ve made to the talent trees have greatly improved the user experience.

I’d like to request a feature that extends these enhancements to the spell book window, with an emphasis on optimizing space usage. Currently, the updated spell book for TWW takes up a significant amount of space, and when opened in the larger version, it prevents other windows from being opened simultaneously. This can be quite limiting during gameplay, as it hinders multitasking.

Why this is important:

Consistency: Applying the same enhancements to the spell book would provide a uniform experience between the talent trees and the spell book, enhancing usability.
Space Optimization: A more compact or adjustable spell book window would allow players to keep other important windows open at the same time, improving multitasking capabilities.
Efficiency: Reducing the space taken up by the spell book would streamline the interface, making it more efficient and less obtrusive during gameplay.
By addressing the space issue while incorporating the beneficial tweaks already present in the talent trees, this feature would significantly improve the addon’s overall utility.

Thank you for considering this request!

Best regards,
Tex (I_AM_T3X)

**Comment by Numynum** [comment]
what changes are you thinking of?
currently I'm thinking to apply the transparent background to the spellbook as well, and CTRL-scroll to resize
neither of them resolve the multitasking issues

Changing the search is something I don't plan on, since I suspect it will badly break things

And I'm not sure what else would be good

When it comes to the spellbook (and talent ui) blocking other windows from opening, you can install https://www.curseforge.com/wow/addons/no-auto-close to prevent this; though that isn't something that'll appeal to everyone

**Comment by I-AM-T3X** [comment]
that sounds great to me, maybe the only thing i think of adding is the ctrl-c to copy spell ID and maybe if there is a way to toggle off the "oh this isn't on your bar" flashing

**Comment by Numynum** [comment]
spellbook background can be made transparent, and CTRL-C to copy spellID is included in latest version
