### ISSUE TITLE
Toggle Skyriding UI button unable to open window (same issue as #38)

### ISSUE THREAD

**Issue by jungheeMW** [NumyAddon/TalentTreeTweaks#43]
Tested on [v1.12.12](https://github.com/NumyAddon/TalentTreeTweaks/releases/tag/v1.12.12). The previous issue from https://github.com/NumyAddon/TalentTreeTweaks/issues/38#issuecomment-2259620774 still persists.

Without addons to disable Blizzard's auto close, the Skyriding UI window will not show when clicking the button from within TTT.

Interestingly enough, the sound effect for opening and closing the window plays, but since TTT is located in the Options panel, and the Options panel cannot be force closed, the Skyriding UI will not show.

**Comment by Numynum** [comment]
so the issue is, that the skyriding UI _was_ being shown, but because I bypassed the panel system, it didn't get a location assigned to it. Since it didn't have any location of where to display the UI, it just didn't render the UI visuals (but sound effects etc were still playing indeed)
but now I tested it with 0 addons, so it should work this time 😛
