### ISSUE TITLE
Issue importing feral talents 

### ISSUE THREAD

**Issue by ElvLegion** [NumyAddon/TalentTreeTweaks#48]
Getting a weird issue trying to import feral druid talents import string is reporting as corrupt node type mismatch at nodeid 99805. First option will be selected 

Talent string imports correctly without the addon just fails with addon .

**Comment by Numynum** [comment]
please add the talent string you tried to import

**Comment by ElvLegion** [comment]
CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMz2sZmFmxMz2sxYbmZm5BmZAAAAAAWCGzAGzMjmZMDzMGzw2YAAAAAAAAGAAAAAgZZmlmtZWGYmB

It looks like the issue is its not properly selecting the hero talent tree cause once I swap it over to wild stalker manually things are ok

**Comment by Numynum** [comment]
it looks like that talent string is actually just incorrect, where did you get it from?
`CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMz2sZmFmxMz2sxYbmZm5BmZAAAAAAWCGzAGzMjmZMDzMGzw2YAAAAAAAAGAAQACAmlZWa2mZZDmZA` looks to be the correct one (which is almost identical)
if you check your string on wowhead for example, it's also incorrect

and after testing it, it imports just fine with this addon, the message in chat is a warning, and that's because there's no hero talent selected in your talent string, so the addon just blindly picks the first one, in the hopes that it's at least mostly going to be OK 🙂

**Comment by ElvLegion** [comment]
Got it from warcraft logs. When I import it with out the addon it works correctly.

**Comment by Numynum** [comment]
for me it does not import correctly (when I have 0 addons loaded), it does not select the hero spec properly
